services:
  - type: web
    name: garba
    plan: free
    autoDeploy: false
    runtime: docker
    repo: https://github.com/nasinamuna/render.git
    envVars:
      - key: PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: garba-db
          property: connectionString
      - key: APP_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: array
      - key: FILESYSTEM_PUBLIC_DISK
        value: public
      - key: FILESYSTEM_PRIVATE_DISK
        value: local
databases:
  - name: garba-db
    plan: free
